workers_per_gpu: 8
distributed: False
amp_enabled: True

model:
  name: minkunet #spvcnn

data:
  num_classes: 12 #22 #19
  ignore_label: 0 #0
  training_size: 19132
  label_mapping: "./configs/label_mapping/da_wod_nuscenes/wod_mapped.yaml"

train:
  seed: 1588147245
  deterministic: False

dataset:
  name: basemodels
  root: dataset/semantic-kitti
  num_points: 160000
  voxel_size: 0.05

num_epochs: 40 #15
batch_size: 4 #16

criterion:
  name: cross_entropy
  ignore_index: 0

optimizer:
  name: sgd
  lr: 2.4e-1
  weight_decay: 1.0e-4
  momentum: 0.9
  nesterov: true

scheduler:
  name: cosine_warmup

###################
## Data_loader options
data_path:
  train_data_loader:
    data_path: "/mnt/personal/gebreawe/Datasets/RealWorld/WOD/processed/Labeled_32_beam/training"
    split: "train"

  val_data_loader:
    data_path: "/mnt/personal/gebreawe/Datasets/RealWorld/WOD/processed/Labeled_32_beam/validation"
    split: "val"

  test_data_loader:
    data_path: "/mnt/personal/gebreawe/Datasets/RealWorld/NUSCENES/processed/val"
    split: "test"

  ssl_data_loader:
    data_path: "/mnt/personal/gebreawe/Datasets/RealWorld/NUSCENES/processed/train"
    split: "pseudo"

###################
## test params
train_params:
  model_path: "/home/gebreawe/Code/Segmentation/T-UDA/weights"
  teacher_model_path: ""
  student_model_path: ""
  checkpoint_every_n_steps: 1000
  max_num_epochs: 40
  ema_start_epoch: 20
  eval_every_n_steps: 1000
  learning_rate: 0.001
  past: 1
  future: 1
  source: 'wod'
  target: 'nuscenes'
  ssl: False
  rgb: False
  uda: True
  time: True
  S_sensor_zpose: 0.0 #
  T_sensor_zpose: 0.0 #

test_params:
  past: 0
  future: 0
  source: 'wod'
  target: 'nuscenes'
  ssl: False
  rgb: False
  uda: True
  time: True
  S_sensor_zpose: 0.0 #
  T_sensor_zpose: 0.0 #